version: '3.8'

services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}

  microservice-core:
    build:
      context: ./microservice-core
      dockerfile: Dockerfile
    container_name: template
    depends_on:
      - rabbitmq
    environment:
      RABBITMQ_URI: ${RABBITMQ_URI}
    command: ["pm2-runtime", "dist/main.js"]
